"""
Field position tables for the four Weather Display clientraw*.txt formats.

Transcribed from hsdn/wdparser (src/WeatherDisplay.php), which documents
compatibility with Weather-Display ver. 10.37R build 296 -- the exact
version embedded in this project's templates' trailing markers
(e.g. "!!C10.37S152!!"). Field order and block lengths were cross-checked
against the real templates in templates/: clientrawextra.txt matches this
table exactly (820 fields); clientrawdaily.txt matches once the source's
own documented "optional" trailing 7_days_indoor_temperature block is
excluded (443 fields). clientraw.txt and clientrawhour.txt each have a
handful of undocumented trailing fields before their banner, which are
intentionally left unmapped (kept as template passthrough).

Each field entry is (name, skip, count): position advances by `skip` then
the field occupies `count` consecutive slots starting there, matching the
original PHP parser's positional algorithm exactly.
"""
from __future__ import annotations

FieldTable = list[tuple[str, int, int]]

CLIENTRAW_FIELDS: FieldTable = [
    ("header", 0, 1),
    ("average_wind_speed", 0, 1),
    ("gust_speed", 0, 1),
    ("wind_direction", 0, 1),
    ("temperature", 0, 1),
    ("humidity", 0, 1),
    ("barometer", 0, 1),
    ("day_rain", 0, 1),
    ("month_rain", 0, 1),
    ("year_rain", 0, 1),
    ("rain_rate", 0, 1),
    ("rain_rate_max", 0, 1),
    ("indoor_temperature", 0, 1),
    ("indoor_humidity", 0, 1),
    ("soil_temperature", 0, 1),
    ("forecast_icon", 0, 1),
    ("wmr968_extra_temperature", 0, 1),
    ("wmr968_extra_humidity", 0, 1),
    ("wmr968_extra_sensor", 0, 1),
    ("yesterday_rain", 0, 1),
    ("extra_temp_sensor_1", 0, 1),
    ("extra_temp_sensor_2", 0, 1),
    ("extra_temp_sensor_3", 0, 1),
    ("extra_temp_sensor_4", 0, 1),
    ("extra_temp_sensor_5", 0, 1),
    ("extra_temp_sensor_6", 0, 1),
    ("extra_hum_sensor_1", 0, 1),
    ("extra_hum_sensor_2", 0, 1),
    ("extra_hum_sensor_3", 0, 1),
    ("hour", 0, 1),
    ("minute", 0, 1),
    ("seconds", 0, 1),
    ("station_name", 0, 1),
    ("dallas_lighting_count", 0, 1),
    ("solar_reading", 0, 1),
    ("day", 0, 1),
    ("month", 0, 1),
    ("wmr968_batt_1", 0, 1),
    ("wmr968_batt_2", 0, 1),
    ("wmr968_batt_3", 0, 1),
    ("wmr968_batt_4", 0, 1),
    ("wmr968_batt_5", 0, 1),
    ("wmr968_batt_6", 0, 1),
    ("wmr968_batt_7", 0, 1),
    ("wind_chill", 0, 1),
    ("humidity_index", 0, 1),
    ("day_temperature_max", 0, 1),
    ("day_temperature_min", 0, 1),
    ("icon_type", 0, 1),
    ("weather_description", 0, 1),
    ("barometer_trend", 0, 1),
    ("20_hours_wind_speed", 0, 20),
    ("day_gust_speed_max", 0, 1),
    ("dewpoint_temperature", 0, 1),
    ("cloud_height", 0, 1),
    ("date", 0, 1),
    ("humidity_index_max", 0, 1),
    ("humidity_index_min", 0, 1),
    ("wind_chill_max", 0, 1),
    ("wind_chill_min", 0, 1),
    ("davis_vp_uv", 0, 1),
    ("hr_wind_speed", 0, 10),
    ("hr_temperature", 0, 10),
    ("hr_rain", 0, 10),
    ("heat_index_max", 0, 1),
    ("heat_index_min", 0, 1),
    ("heat_index", 0, 1),
    ("average_wind_speed_max", 0, 1),
    ("last_minute_lightning", 0, 1),
    ("last_lightning_strike_time", 0, 1),
    ("last_lightning_strike_date", 0, 1),
    ("wind_average_direction", 0, 1),
    ("nexstorm_dist", 0, 1),
    ("nexstorm_bearing", 0, 1),
    ("extra_temp_sensor_7", 0, 1),
    ("extra_temp_sensor_8", 0, 1),
    ("extra_hum_sensor_4", 0, 1),
    ("extra_hum_sensor_5", 0, 1),
    ("extra_hum_sensor_6", 0, 1),
    ("extra_hum_sensor_7", 0, 1),
    ("extra_hum_sensor_8", 0, 1),
    ("vp_solarwm", 0, 1),
    ("max_intemp", 0, 1),
    ("min_intemp", 0, 1),
    ("apparent_temperature", 0, 1),
    ("barometer_max", 0, 1),
    ("barometer_min", 0, 1),
    ("gust_speed_last_hour_max", 0, 1),
    ("gust_speed_last_hour_max_time", 0, 1),
    ("gust_speed_today_max_time", 0, 1),
    ("apparent_temperature_max", 0, 1),
    ("apparent_temperature_min", 0, 1),
    ("dew_pt_max", 0, 1),
    ("dew_pt_min", 0, 1),
    ("gust_speed_in_l_minute_max", 0, 1),
    ("year", 0, 1),
    ("thsws", 0, 1),
    ("temperature_trend", 0, 1),
    ("humidity_trend", 0, 1),
    ("humidity_index_trend", 0, 1),
    ("hr_wind_direction", 0, 10),
    ("leaf_wetness", 0, 1),
    ("soil_moisture", 0, 1),
    ("10_minutes_average_wind_speed", 0, 1),
    ("wet_bulb_temperature", 0, 1),
    ("latitude", 0, 1),
    ("longitude", 0, 1),
    ("9am_rain_reset_total", 0, 1),
    ("day_humidity_max", 0, 1),
    ("day_humidity_min", 0, 1),
    ("midnight_reset_rain_total", 0, 1),
    ("windchill_min_time", 0, 1),
    ("cost_channel_1", 0, 1),
    ("cost_channel_2", 0, 1),
    ("cost_channel_3", 0, 1),
    ("cost_channel_4", 0, 1),
    ("cost_channel_5", 0, 1),
    ("cost_channel_6", 0, 1),
    ("day_wind_run", 0, 1),
    ("day_temperature_max_time", 0, 1),
    ("day_temperature_min_time", 0, 1),
]

CLIENTRAWHOUR_FIELDS: FieldTable = [
    ("header", 0, 1),
    ("wind_speed", 0, 60),
    ("gust_speed", 0, 60),
    ("wind_direction", 0, 60),
    ("temperature", 0, 60),
    ("humidity", 0, 60),
    ("barometer", 0, 60),
    ("rain_total", 0, 60),
    ("minutes_solar_data", 0, 60),
    ("hours_solar_data", 0, 95),
    ("hours_uv_data", 0, 95),
]

CLIENTRAWDAILY_FIELDS: FieldTable = [
    ("header", 0, 1),
    ("day_temperature_max", 0, 31),
    ("day_temperature_min", 0, 31),
    ("month_rain_month", 0, 31),
    ("month_barometer", 0, 31),
    ("month_wind_speed", 0, 31),
    ("month_wind_direction", 0, 31),
    ("12_months_rain_total", 0, 12),
    ("month_humdity", 0, 31),
    ("hour", 0, 1),
    ("minute", 0, 1),
    ("seconds", 0, 1),
    ("7_days_temperature", 0, 28),
    ("7_days_barometer", 0, 28),
    ("7_days_humidity", 0, 28),
    ("7_days_wind_direction", 0, 28),
    ("7_days_wind_speed", 0, 28),
    ("7_days_solar", 0, 28),
    ("7_days_uv", 0, 28),
    ("year_rain_total", 0, 1),
    ("rain_average", 0, 12),
    # NOTE: upstream also documents a trailing optional '7_days_indoor_temperature'
    # (0, 28) block here. Our real clientrawdaily.txt template (443 fields) does not
    # include it -- confirmed by exact field-count match without it. Left out on purpose.
]

CLIENTRAWEXTRA_FIELDS: FieldTable = [
    ("header", 0, 1),
    ("20_hours_wind_speed", 0, 20),
    ("20_hours_temperature", 0, 20),
    ("20_hours_rain", 0, 20),
    ("record_month_temperature_max", 0, 6),
    ("record_month_temperature_min", 0, 6),
    ("record_month_high_gust_speed", 0, 6),
    ("record_month_rain_rate", 0, 6),
    ("record_month_barometer_min", 0, 6),
    ("record_month_barometer_max", 0, 6),
    ("record_month_daily_rain", 0, 6),
    ("record_month_rain_1_hour", 0, 6),
    ("record_month_average_wind_speed", 0, 6),
    ("record_month_soil_max", 6, 6),
    ("record_month_soil_min", 0, 6),
    ("record_month_wind_chill_min", 0, 6),
    ("record_month_gust_direction_max", 0, 6),
    ("record_month_average_wind_speed_direction", 0, 6),
    ("record_month_warmest_day", 0, 6),
    ("record_month_coldest_night", 0, 6),
    ("record_month_coldest_day", 0, 6),
    ("record_month_warmest_night", 0, 6),
    ("record_month_heat_index_max", 0, 6),
    ("record_month_grass_max", 0, 6),
    ("record_year_temperature_max", 0, 6),
    ("record_year_temperature_min", 0, 6),
    ("record_year_high_gust_speed", 0, 6),
    ("record_year_rain_rate", 0, 6),
    ("record_year_barometer_min", 0, 6),
    ("record_year_barometer_max", 0, 6),
    ("record_year_daily_rain", 0, 6),
    ("record_year_rain_1_hour", 0, 6),
    ("record_year_average_wind_speed", 0, 6),
    ("record_year_soil_max", 6, 6),
    ("record_year_soil_min", 0, 6),
    ("record_year_wind_chill_min", 0, 6),
    ("record_year_gust_direction_max", 0, 6),
    ("record_year_average_wind_speed_direction", 0, 6),
    ("record_year_warmest_day", 0, 6),
    ("record_year_coldest_night", 0, 6),
    ("record_year_coldest_day", 0, 6),
    ("record_year_warmest_night", 0, 6),
    ("record_year_heat_index_max", 0, 6),
    ("record_year_grass_max", 0, 6),
    ("record_alltime_temperature_max", 0, 6),
    ("record_alltime_temperature_min", 0, 6),
    ("record_alltime_high_gust_speed", 0, 6),
    ("record_alltime_rain_rate", 0, 6),
    ("record_alltime_barometer_min", 0, 6),
    ("record_alltime_barometer_max", 0, 6),
    ("record_alltime_daily_rain", 0, 6),
    ("record_alltime_rain_1_hour", 0, 6),
    ("record_alltime_average_wind_speed", 0, 6),
    ("record_alltime_soil_max", 6, 6),
    ("record_alltime_soil_min", 0, 6),
    ("record_alltime_wind_chill_min", 0, 6),
    ("record_alltime_gust_direction_max", 0, 6),
    ("record_alltime_average_wind_speed_direction", 0, 6),
    ("record_alltime_warmest_day", 0, 6),
    ("record_alltime_coldest_night", 0, 6),
    ("record_alltime_coldest_day", 0, 6),
    ("record_alltime_warmest_night", 0, 6),
    ("record_alltime_heat_index_max", 0, 6),
    ("record_alltime_grass_max", 0, 6),
    ("20_hours_barometer", 0, 20),
    ("20_hours_timestamp", 0, 20),
    ("snow_for_the_day", 0, 1),
    ("snow_for_the_month", 0, 1),
    ("snow_for_the_season", 0, 1),
    ("days_since_last_rain", 0, 1),
    ("days_of_rain_this_month", 0, 1),
    ("7_days_rain", 0, 7),
    ("20_hours_solar_reading", 0, 20),
    ("20_hours_uv_reading", 0, 20),
    ("davis_vp_forecast_text", 0, 1),
    ("et_value", 0, 1),
    ("vpp_et_value", 0, 1),
    ("yesterday_rain", 0, 1),
    ("wd_version", 0, 1),
    ("20_hours_wind_direction", 0, 20),
    ("sunrise", 0, 1),
    ("sunset", 0, 1),
    ("moonrise", 0, 1),
    ("moonset", 0, 1),
    ("moon_phase", 0, 1),
    ("moon_age", 0, 1),
    ("24_hours_wind_speed", 0, 4),
    ("24_hours_temperature", 0, 4),
    ("24_hours_rain", 0, 4),
    ("24_hours_barometer", 0, 4),
    ("24_hours_timestamp", 0, 4),
    ("24_hours_solar_reading", 0, 4),
    ("24_hours_uv_reading", 0, 4),
    ("24_hours_wind_direction", 0, 4),
    ("extra_temp_sensor_1_max", 0, 1),
    ("extra_temp_sensor_1_min", 0, 1),
    ("extra_temp_sensor_2_max", 0, 1),
    ("extra_temp_sensor_2_min", 0, 1),
    ("extra_temp_sensor_3_max", 0, 1),
    ("extra_temp_sensor_3_min", 0, 1),
    ("extra_temp_sensor_4_max", 0, 1),
    ("extra_temp_sensor_4_min", 0, 1),
    ("extra_temp_sensor_5_max", 0, 1),
    ("extra_temp_sensor_5_min", 0, 1),
    ("extra_temp_sensor_6_max", 0, 1),
    ("extra_temp_sensor_6_min", 0, 1),
    ("extra_temp_sensor_7_max", 0, 1),
    ("extra_temp_sensor_7_min", 0, 1),
    ("extra_temp_sensor_8_max", 0, 1),
    ("extra_temp_sensor_8_min", 0, 1),
    ("day_night_flag", 0, 1),
    ("24_hours_humidity", 0, 24),
    ("fwi_value", 0, 1),
    ("24_hours_indoor_temperature", 0, 24),
    ("record_month_solar_max", 0, 6),
    ("record_month_uv_max", 0, 6),
    ("record_year_solar_max", 0, 6),
    ("record_year_uv_max", 0, 6),
    ("record_alltime_solar_max", 0, 6),
    ("record_alltime_uv_max", 0, 6),
    ("sunshine_hours", 0, 1),
    ("snow_depth", 0, 1),
    ("hour", 0, 1),
    ("minute", 0, 1),
    ("seconds", 0, 1),
    ("flag_solar_data", 0, 1),
    ("flag_uv_data", 0, 1),
    ("flag_soil_temperature_data", 0, 1),
    ("24_hours_lightning", 0, 24),
    ("wdl_weather_warn_flag", 0, 1),
    ("record_month_dew_max", 0, 6),
    ("record_month_dew_min", 0, 6),
    ("record_year_dew_max", 0, 6),
    ("record_year_dew_min", 0, 6),
    ("record_alltime_dew_max", 0, 6),
    ("record_alltime_dew_min", 0, 6),
    ("chandler_burning_index", 0, 1),
    ("visibility", 0, 1),
    ("yesterday_temperature_max", 0, 1),
    ("yesterday_temperature_min", 0, 1),
    ("yesterday_temperature_max_time", 0, 1),
    ("yesterday_temperature_min_time", 0, 1),
    ("yesterday_barometer_max", 0, 1),
    ("yesterday_barometer_min", 0, 1),
    ("yesterday_barometer_max_time", 0, 1),
    ("yesterday_barometer_min_time", 0, 1),
    ("yesterday_humidity_max", 0, 1),
    ("yesterday_humidity_min", 0, 1),
    ("yesterday_humidity_max_time", 0, 1),
    ("yesterday_humidity_min_time", 0, 1),
    ("yesterday_gust_speed_max", 0, 1),
    ("yesterday_gust_speed_max_time", 0, 1),
    ("yesterday_average_wind_speed_max", 0, 1),
    ("yesterday_average_wind_speed_max_time", 0, 1),
    ("yesterday_wind_chill_min", 0, 1),
    ("yesterday_wind_chill_min_time", 0, 1),
    ("yesterday_max_heat", 0, 1),
    ("yesterday_max_heat_time", 0, 1),
    ("yesterday_dew_max", 0, 1),
    ("yesterday_dew_min", 0, 1),
    ("yesterday_dew_max_time", 0, 1),
    ("yesterday_dew_min_time", 0, 1),
    ("yesterday_solar_max", 0, 1),
    ("yesterday_solar_max_time", 0, 1),
    ("today_temperature_max", 0, 1),
    ("today_temperature_min", 0, 1),
    ("today_temperature_max_time", 0, 1),
    ("today_temperature_min_time", 0, 1),
    ("today_barometer_max", 0, 1),
    ("today_barometer_min", 0, 1),
    ("today_barometer_max_time", 0, 1),
    ("today_barometer_min_time", 0, 1),
    ("today_humidity_max", 0, 1),
    ("today_humidity_min", 0, 1),
    ("today_humidity_max_time", 0, 1),
    ("today_humidity_min_time", 0, 1),
    ("today_gust_speed_max", 0, 1),
    ("today_gust_speed_max_time", 0, 1),
    ("today_average_wind_speed_max", 0, 1),
    ("today_average_wind_speed_max_time", 0, 1),
    ("today_wind_chill_min", 0, 1),
    ("today_wind_chill_min_time", 0, 1),
    ("today_max_heat", 0, 1),
    ("today_max_heat_time", 0, 1),
    ("today_dew_max", 0, 1),
    ("today_dew_min", 0, 1),
    ("today_dew_max_time", 0, 1),
    ("today_dew_min_time", 0, 1),
    ("today_solar_max", 0, 1),
    ("today_solar_max_time", 0, 1),
]


def field_positions(table: FieldTable) -> dict[str, tuple[int, int]]:
    """Return {field_name: (start_index, count)} using the original parser's
    positional algorithm (skip then consume, in table order)."""
    pos = 0
    positions: dict[str, tuple[int, int]] = {}
    for name, skip, count in table:
        pos += skip
        positions[name] = (pos, count)
        pos += count
    return positions


CLIENTRAW_POSITIONS = field_positions(CLIENTRAW_FIELDS)
CLIENTRAWHOUR_POSITIONS = field_positions(CLIENTRAWHOUR_FIELDS)
CLIENTRAWDAILY_POSITIONS = field_positions(CLIENTRAWDAILY_FIELDS)
CLIENTRAWEXTRA_POSITIONS = field_positions(CLIENTRAWEXTRA_FIELDS)
